name: Update Cat JSON

on:
  push:
    branches:
      - main
    paths:
      - 'public/cats/*'  # This makes sure the action runs whenever an image is added or changed in the cats folder

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Randomly select a cat image and update cat.json
      run: |
        # Select a random cat image from the public/cats directory
        IMAGE=$(ls public/cats | shuf -n 1)
        
        # Create the cat.json content
        echo "{\"image\": \"/cats/$IMAGE\"}" > public/cat.json

    - name: Commit and push cat.json update
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add public/cat.json
        git commit -m "Update cat.json with random image"
        git push
